function s = prtUtilLicense

% Copyright (c) 2013 New Folder Consulting
%
% Permission is hereby granted, free of charge, to any person obtaining a
% copy of this software and associated documentation files (the
% "Software"), to deal in the Software without restriction, including
% without limitation the rights to use, copy, modify, merge, publish,
% distribute, sublicense, and/or sell copies of the Software, and to permit
% persons to whom the Software is furnished to do so, subject to the
% following conditions:
%
% The above copyright notice and this permission notice shall be included
% in all copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
% OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
% NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
% DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
% OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
% USE OR OTHER DEALINGS IN THE SOFTWARE.


s = cat(2,'% Copyright (c) 2013 New Folder Consulting',char(10), '%', char(10),...
    '% Permission is hereby granted, free of charge, to any person obtaining a',char(10),...
    '% copy of this software and associated documentation files (the',char(10),...
    '% "Software"), to deal in the Software without restriction, including',char(10),...
    '% without limitation the rights to use, copy, modify, merge, publish,',char(10),...
    '% distribute, sublicense, and/or sell copies of the Software, and to permit',char(10),...
    '% persons to whom the Software is furnished to do so, subject to the',char(10),...
    '% following conditions:',char(10),'%',char(10),...
    '% The above copyright notice and this permission notice shall be included',char(10),...
    '% in all copies or substantial portions of the Software.',char(10), '%', char(10), ...
    '% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS', char(10), ...
    '% OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF', char(10), ...
    '% MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN', char(10), ...
    '% NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,', char(10), ...
    '% DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR', char(10), ...
    '% OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE', char(10), ...
    '% USE OR OTHER DEALINGS IN THE SOFTWARE.');
